/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AbstractFactory;

import Sql.SqlVeriIslemleriCalisan;
import Sql.SqlVeriIslemleriDepo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import nesneproje.Calisan;
import nesneproje.Personel;
import nesneproje.Yonetici;

/**
 *
 * @author taha
 */
public class CalisanPage extends javax.swing.JFrame {

    /**
     * Creates new form CalisanPage
     */
    public CalisanPage(String a) {
        initComponents();
        String mevki = a;
        jTable3.setVisible(false);
        jLabel10.setVisible(false);
        personel_mevki.setVisible(false);
        if (mevki.equals("CEO")) {
            jTable3.setVisible(true);
            jLabel10.setVisible(true);
            personel_mevki.setVisible(true);
        }
        if (mevki.equals("Yönetici")) {
            personel_mevki.setSelectedItem("Personel");

        }

        Personel p = new Personel();
        Yonetici y = new Yonetici();
        List<Calisan> veri = p.TumCalısanGoster();
        DefaultTableModel dfTable = (DefaultTableModel) jTable4.getModel();
        dfTable.setRowCount(0);
        for (Calisan c : veri) {
            Object[] obj = {c.getTc(), "**************", Character.toUpperCase(c.getUlke().charAt(0)) + c.getUlke().substring(1), Character.toUpperCase(c.getIsim().charAt(0)) + c.getIsim().substring(1), Character.toUpperCase(c.getSoyad().charAt(0)) + c.getSoyad().substring(1), c.getTelefonNo(), c.getMevki(), c.getMaas(), c.getOrtalamaCalısmaSaati()};
            dfTable.addRow(obj);
        }
        JTable ceoTablo = jTable3;
        List<Calisan> ceoVeri = y.TumCalısanGoster();
        DefaultTableModel dfTableD = (DefaultTableModel) ceoTablo.getModel();
        dfTableD.setRowCount(0);
        for (Calisan c : ceoVeri) {
            Object[] obj = {c.getTc(), "**************", Character.toUpperCase(c.getUlke().charAt(0)) + c.getUlke().substring(1), Character.toUpperCase(c.getIsim().charAt(0)) + c.getIsim().substring(1), Character.toUpperCase(c.getSoyad().charAt(0)) + c.getSoyad().substring(1), c.getTelefonNo(), c.getMevki(), c.getMaas(), c.getOrtalamaCalısmaSaati()};
            if (c.getMevki().equals("Yönetici")) {
                dfTableD.addRow(obj);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        personel_isim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        silBtn = new javax.swing.JButton();
        personel_tc = new javax.swing.JTextField();
        personel_soyad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        personel_ulke = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        personel_sifre = new javax.swing.JTextField();
        personel_numara = new javax.swing.JTextField();
        personel_maas = new javax.swing.JTextField();
        personel_ort_calisma = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        personel_mevki = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Ülke");

        jLabel5.setText("Şifre");

        personel_isim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_isimActionPerformed(evt);
            }
        });

        jLabel6.setText("TC");

        jTable3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tc", "sifre", "ulke", "isim", "soyad", "numara", "mevki", "maas", "ortcalısmasaati"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(0, 0, 0));
        jTable3.setOpaque(false);
        jTable3.setShowGrid(true);
        jScrollPane2.setViewportView(jTable3);

        silBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        silBtn.setText("Sil");
        silBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silBtnActionPerformed(evt);
            }
        });

        personel_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_tcActionPerformed(evt);
            }
        });

        personel_soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_soyadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("ÇALIŞAN MENÜSÜ");

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        personel_ulke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amerika", "Turkiye" }));
        personel_ulke.setToolTipText("");
        personel_ulke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_ulkeActionPerformed(evt);
            }
        });

        jLabel2.setText("İsim");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel7.setText("Personel Tablosu");

        jLabel3.setText("Soyad");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel8.setText("Yönetici Tablosu");

        jTable4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tc", "sifre", "ulke", "isim", "soyad", "numara", "mevki", "maas", "ortcalısmasaati"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setGridColor(new java.awt.Color(0, 0, 0));
        jTable4.setOpaque(false);
        jTable4.setShowGrid(true);
        jScrollPane4.setViewportView(jTable4);

        personel_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_sifreActionPerformed(evt);
            }
        });

        personel_numara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_numaraActionPerformed(evt);
            }
        });

        personel_maas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_maasActionPerformed(evt);
            }
        });

        personel_ort_calisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_ort_calismaActionPerformed(evt);
            }
        });

        jLabel10.setText("Mevki");

        jLabel11.setText("Numara");

        jLabel12.setText("Maaş");

        jLabel13.setText("Ortalama Çalışma Saati");

        personel_mevki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yönetici", "Personel" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(personel_mevki, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(personel_soyad)
                                    .addComponent(personel_tc)
                                    .addComponent(personel_ulke, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(personel_isim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(personel_sifre)
                                    .addComponent(personel_numara)
                                    .addComponent(personel_maas, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(personel_ort_calisma)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(360, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 385, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personel_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_numara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personel_ort_calisma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(personel_mevki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personel_isimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_isimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_isimActionPerformed

    private void sil() {
        Yonetici y = new Yonetici();
        if (jTable3.getSelectedRow() > -1) {
            long tc = (long) jTable3.getValueAt(jTable3.getSelectedRow(), 0);
            y.İstenCıkarım(tc);
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.setRowCount(0);

        } else if (jTable4.getSelectedRow() > -1) {
            long tc = (long) jTable4.getValueAt(jTable4.getSelectedRow(), 0);
            y.İstenCıkarım(tc);
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
            model.setRowCount(0);

        }
        tabloGuncelle();
    }
    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed
        sil();

    }//GEN-LAST:event_silBtnActionPerformed

    private void personel_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_tcActionPerformed

    private void personel_soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_soyadActionPerformed

    private void kaydet() {
        try {
            String an = "";
            if (jTable3.getSelectedRow() > -1) {
                tableChanged(jTable3);
            } else if (jTable4.getSelectedRow() > -1) {
                tableChanged(jTable4);
            } else {
                Yonetici y = new Yonetici();
                JTable ceoTablo = jTable3;
                JTable yoneticiTablo = jTable4;
                DefaultTableModel ceo = (DefaultTableModel) ceoTablo.getModel();
                DefaultTableModel yon = (DefaultTableModel) yoneticiTablo.getModel();
                ceo.setRowCount(0);
                yon.setRowCount(0);
                long numara = Long.parseLong(personel_numara.getText());
                an = y.İsealma(Long.parseLong(personel_tc.getText()), personel_ulke.getSelectedItem().toString(), personel_isim.getText(), personel_sifre.getText(), personel_soyad.getText(), personel_numara.getText(), Integer.parseInt(personel_maas.getText()), Integer.parseInt(personel_ort_calisma.getText()), personel_mevki.getSelectedItem().toString());
                JOptionPane.showMessageDialog(null, an, "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            }

            tabloGuncelle();
            JTable ceoTablo = jTable3;
            SqlVeriIslemleriCalisan d = new SqlVeriIslemleriCalisan();
            List<Calisan> ceoVeri = d.Verileri_Listeleme();
            DefaultTableModel dfTableD = (DefaultTableModel) ceoTablo.getModel();
            dfTableD.setRowCount(0);
            for (Calisan c : ceoVeri) {
                if (c.getMevki().equals("Yönetici")) {
                    Object[] obj = {c.getTc(), "********", Character.toUpperCase(c.getUlke().charAt(0)) + c.getUlke().substring(1), Character.toUpperCase(c.getIsim().charAt(0)) + c.getIsim().substring(1), Character.toUpperCase(c.getSoyad().charAt(0)) + c.getSoyad().substring(1), c.getTelefonNo(), c.getMevki(), c.getMaas(), c.getOrtalamaCalısmaSaati()};
                    dfTableD.addRow(obj);
                }
            }
            personel_tc.setText("");
            personel_numara.setText("");
            personel_ort_calisma.setText("");
            personel_isim.setText("");
            personel_soyad.setText("");
            personel_maas.setText("");
            personel_sifre.setText("");

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "HATA!", "Uyarı", JOptionPane.INFORMATION_MESSAGE);
            tabloGuncelle();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        kaydet();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void personel_ulkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_ulkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_ulkeActionPerformed

    private void personel_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_sifreActionPerformed

    private void personel_numaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_numaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_numaraActionPerformed

    private void personel_maasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_maasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_maasActionPerformed

    private void personel_ort_calismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_ort_calismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personel_ort_calismaActionPerformed

    private void tabloGuncelle() {
        JTable tablo = jTable4;
        Personel p = new Personel();
        Yonetici y = new Yonetici();

        List<Personel> veri = p.TumCalısanGoster();
        DefaultTableModel dfTable = (DefaultTableModel) tablo.getModel();
        dfTable.setRowCount(0);
        for (Personel c : veri) {
            Object[] obj = {c.getTc(), "**************", Character.toUpperCase(c.getUlke().charAt(0)) + c.getUlke().substring(1), Character.toUpperCase(c.getIsim().charAt(0)) + c.getIsim().substring(1), Character.toUpperCase(c.getSoyad().charAt(0)) + c.getSoyad().substring(1), c.getTelefonNo(), c.getMevki(), c.getMaas(), c.getOrtalamaCalısmaSaati()};
            dfTable.addRow(obj);
        }

        JTable ceoTablo = jTable3;
        Yonetici yo = new Yonetici();
        List<Calisan> ceoVeri = yo.TumCalısanGoster();
        DefaultTableModel dfTableD = (DefaultTableModel) ceoTablo.getModel();
        dfTableD.setRowCount(0);
        for (Calisan c : ceoVeri) {
            Object[] obj = {c.getTc(), "**************", Character.toUpperCase(c.getUlke().charAt(0)) + c.getUlke().substring(1), Character.toUpperCase(c.getIsim().charAt(0)) + c.getIsim().substring(1), Character.toUpperCase(c.getSoyad().charAt(0)) + c.getSoyad().substring(1), c.getTelefonNo(), c.getMevki(), c.getMaas(), c.getOrtalamaCalısmaSaati()};
            if (c.getMevki().equals("Yönetici")) {
                dfTableD.addRow(obj);
            }
        }

    }

    private void tableChanged(JTable table) {
        String an = "Girilen Bilgiler Hatalı";
        Yonetici y = new Yonetici();
        int row = table.getSelectedRow(); // Seçilen satırın indeksi
        int column = table.getSelectedColumn(); // Seçilen sütunun indeksi
        String cName = table.getColumnName(column);
        Object data = table.getValueAt(row, column); // Seçilen hücrenin değeri
        long tc = (long) table.getValueAt(table.getSelectedRow(), 0);
        if (column == 2 || column == 5 || column == 6) {
            an = y.BilgiGuncelle(tc, 0, data.toString(), cName, 0);
            JOptionPane.showMessageDialog(null, an, "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        }
        if (column == 8) {
            an = y.BilgiGuncelle(tc, (Integer) data, "", cName, 0);
            JOptionPane.showMessageDialog(null, an, "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        }
        if (column == 7) {
            an = y.MaasGuncelle(tc, (Integer) data);
            JOptionPane.showMessageDialog(null, an, "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        }

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        tabloGuncelle();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalisanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalisanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalisanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalisanPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable3;
    public javax.swing.JTable jTable4;
    private javax.swing.JTextField personel_isim;
    private javax.swing.JTextField personel_maas;
    private javax.swing.JComboBox<String> personel_mevki;
    private javax.swing.JTextField personel_numara;
    private javax.swing.JTextField personel_ort_calisma;
    private javax.swing.JTextField personel_sifre;
    private javax.swing.JTextField personel_soyad;
    private javax.swing.JTextField personel_tc;
    private javax.swing.JComboBox<String> personel_ulke;
    private javax.swing.JButton silBtn;
    // End of variables declaration//GEN-END:variables
}
