/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AbstractFactory;

import Sql.SqlVeriIslemleriCalisan;
import Sql.SqlVeriIslemleriSatis;
import Sql.SqlVeriIslemleriUlasım;
import Sql.SqlVeriIslemleriUretim;
import TemplateMethod.DenizYoluUlasım;
import TemplateMethod.HavaYoluUlasım;
import TemplateMethod.KaraYoluUlasım;
import TemplateMethod.UlasımYap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import nesneproje.Calisan;
import nesneproje.Personel;
import nesneproje.Yonetici;

/**
 *
 * @author taha
 */
public class SatisPage extends javax.swing.JFrame {

    /**
     * Creates new form SatisPage
     */
    public SatisPage() {
        initComponents();
        SqlVeriIslemleriUretim v = new SqlVeriIslemleriUretim();
        List<Uretim> veri = v.Verileri_Listeleme();
        DefaultTableModel dfTable = (DefaultTableModel) jTable3.getModel();
        for (Uretim c : veri) {
            Object[] obj = {c.uretim_id, c.urun_id, Character.toUpperCase(c.ulke.charAt(0)) + c.ulke.substring(1), Character.toUpperCase(c.urun_ad.charAt(0)) + c.urun_ad.substring(1), Character.toUpperCase(c.urun_renk.charAt(0)) + c.urun_renk.substring(1), c.satılan_miktar, c.maliyet};
            dfTable.addRow(obj);

        }

        SqlVeriIslemleriSatis s = new SqlVeriIslemleriSatis();
        List<Satis> veriSatis = s.Verileri_Listeleme();
        DefaultTableModel satis = (DefaultTableModel) satis_tablo.getModel();
        for (Satis c : veriSatis) {
            Object[] obj = {c.getSatis_id(), c.getUretim_id(), Character.toUpperCase(c.getSatilan_ulke().charAt(0)) + c.getSatilan_ulke().substring(1), Character.toUpperCase(c.getSattigimiz_ulke().charAt(0)) + c.getSattigimiz_ulke().substring(1), Character.toUpperCase(c.getFirma_adi().charAt(0)) + c.getFirma_adi().substring(1), c.getFirma_vergi_no(), c.getFirma_iletisim(), c.getSatilan_urun(), c.getSatilan_urun_renk(), c.getOdeme_turu(), c.getUlasım_yolu(), c.getUlasım_yolu_uzaklık(), c.getSatis_fiyati(), c.getSatılan_desi()};
            satis.addRow(obj);

        }

        SqlVeriIslemleriUlasım u = new SqlVeriIslemleriUlasım();
        List<UlasımYap> veriUlasim = u.Verileri_Listeleme();
        DefaultTableModel ulasim = (DefaultTableModel) ulasim_tablo.getModel();
        for (UlasımYap c : veriUlasim) {
            Object[] obj = {c.getUlasim_id(), c.getSatis_id(), Character.toUpperCase(c.getSattigimiz_ulke().charAt(0)) + c.getSattigimiz_ulke().substring(1), Character.toUpperCase(c.getSatilan_urun().charAt(0)) + c.getSatilan_urun().substring(1), Character.toUpperCase(c.getSatilan_renk().charAt(0)) + c.getSatilan_renk().substring(1), Character.toUpperCase(c.getFirma_iletisim().charAt(0)) + c.getFirma_iletisim().substring(1), Character.toUpperCase(c.getUlasım_yolu().charAt(0)) + c.getUlasım_yolu().substring(1), c.getTeslim_edildimi().toUpperCase(), c.getUlasım_yolu_uzaklık(), c.getSatilan_desi(), c.getUlasım_maliyet(), c.getTahmini_teslimat_gunu()};
            ulasim.addRow(obj);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        satis_tablo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ulasim_tablo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        sattigimiz_ulke = new javax.swing.JTextField();
        firma_adi = new javax.swing.JTextField();
        firma_vergi = new javax.swing.JTextField();
        firma_iletisim = new javax.swing.JTextField();
        uretim_id = new javax.swing.JTextField();
        odeme_turu = new javax.swing.JTextField();
        ulasim_uzaklik = new javax.swing.JTextField();
        ulasim_yolu = new javax.swing.JComboBox<>();
        satis_fiyat = new javax.swing.JTextField();
        satilan_desi = new javax.swing.JTextField();
        kaydetBtn = new javax.swing.JButton();
        silBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel7.setText("Satış Tablosu");

        satis_tablo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        satis_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "satis_id", "uretim_id", "satilan_ulke", "sattigimiz_ulke", "firma_adi", "firma_vergi_no", "firma_iletisim", "satilan_urun", "satilan_urun_renk", "odeme_turu", "ulasim_yolu", "ulasim_yolu_uzaklik", "satis_fiyati", "satilan_desi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true, false, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        satis_tablo.setGridColor(new java.awt.Color(0, 0, 0));
        satis_tablo.setOpaque(false);
        satis_tablo.setShowGrid(true);
        jScrollPane4.setViewportView(satis_tablo);

        ulasim_tablo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ulasim_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ulasim_id", "satis_id", "sattigimiz_ulke", "satilan_urun", "satilan_renk", "firma_iletisim", "ulasım_yolu", "teslim_edildimi", "ulasım_yolu_uzaklık", "satilan_desi", "ulasım_maliyet", "tahmini_teslimat_gunu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ulasim_tablo.setGridColor(new java.awt.Color(0, 0, 0));
        ulasim_tablo.setOpaque(false);
        ulasim_tablo.setShowGrid(true);
        jScrollPane2.setViewportView(ulasim_tablo);

        jTable3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "uretim_id", "urun_id", "uretilen_ulke", "urun_adı", "urun_renk", "uretilen_miktar", "maliyet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(0, 0, 0));
        jTable3.setOpaque(false);
        jTable3.setShowGrid(true);
        jScrollPane3.setViewportView(jTable3);

        uretim_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uretim_idActionPerformed(evt);
            }
        });

        ulasim_uzaklik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulasim_uzaklikActionPerformed(evt);
            }
        });

        ulasim_yolu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hava", "Kara", "Deniz" }));

        kaydetBtn.setText("Kaydet");
        kaydetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetBtnActionPerformed(evt);
            }
        });

        silBtn.setText("Sil");
        silBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel8.setText("Üretim Tablosu");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jLabel9.setText("Ulaşım Tablosu");

        jLabel1.setText("ÜretimID");

        jLabel3.setText("Sattığımız Ülke");

        jLabel5.setText("Firma Adı");

        jLabel6.setText("Firma İletişim");

        jLabel10.setText("Firma Vergi No");

        jLabel11.setText("Teslimat Uzaklığı");

        jLabel12.setText("Ödeme Türü");

        jLabel13.setText("Satış Miktarı(Desisi)");

        jLabel14.setText("Satış Fiyatı");

        jLabel15.setText("Ulaşım Yolu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sattigimiz_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uretim_id, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firma_vergi, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(firma_iletisim, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(firma_adi, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(kaydetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(odeme_turu)
                            .addComponent(satis_fiyat)
                            .addComponent(ulasim_yolu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(satilan_desi)
                            .addComponent(ulasim_uzaklik, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(silBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ulasim_uzaklik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(odeme_turu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(uretim_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sattigimiz_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firma_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firma_vergi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firma_iletisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(satilan_desi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(satis_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ulasim_yolu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kaydetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uretim_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uretim_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uretim_idActionPerformed

    private void ulasim_uzaklikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulasim_uzaklikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ulasim_uzaklikActionPerformed

    private void kaydetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetBtnActionPerformed
        try {

            String an = "";
            if (satis_tablo.getSelectedRow() > -1) {
                tableChanged(satis_tablo);
            } else if (ulasim_tablo.getSelectedRow() > -1) {
                tableChanged(ulasim_tablo);
            } else {
                Satis s = new Satis();
                DefaultTableModel ulasim = (DefaultTableModel) ulasim_tablo.getModel();
                DefaultTableModel satis = (DefaultTableModel) satis_tablo.getModel();
                ulasim.setRowCount(0);
                satis.setRowCount(0);
                if (ulasim_yolu.getSelectedItem().toString().toLowerCase().equals("deniz")) {
                    an = s.SatisEkleme(Integer.parseInt(uretim_id.getText()), sattigimiz_ulke.getText(), firma_adi.getText(), firma_vergi.getText(), firma_iletisim.getText(), odeme_turu.getText(), ulasim_yolu.getSelectedItem().toString(), Integer.parseInt(ulasim_uzaklik.getText()), Integer.parseInt(satis_fiyat.getText()), Integer.parseInt(satilan_desi.getText()));
                    SqlVeriIslemleriSatis sa = new SqlVeriIslemleriSatis();
                    List<Satis> veri = sa.Verileri_Listeleme();
                    for (Satis c : veri) {
                        if (c.uretim_id == Integer.parseInt(uretim_id.getText()) && c.getFirma_vergi_no().toLowerCase().equals(firma_vergi.getText())) {

                            DenizYoluUlasım d = new DenizYoluUlasım();
                            int satılan_desi = Integer.parseInt(satilan_desi.getText());
                            an = d.run(c.getSatis_id(), satılan_desi);
                        }
                    }

                }
                if (ulasim_yolu.getSelectedItem().toString().toLowerCase().equals("hava")) {
                    s.SatisEkleme(Integer.parseInt(uretim_id.getText()), sattigimiz_ulke.getText(), firma_adi.getText(), firma_vergi.getText(), firma_iletisim.getText(), odeme_turu.getText(), ulasim_yolu.getSelectedItem().toString(), Integer.parseInt(ulasim_uzaklik.getText()), Integer.parseInt(satis_fiyat.getText()), Integer.parseInt(satilan_desi.getText()));
                    SqlVeriIslemleriSatis sa = new SqlVeriIslemleriSatis();
                    List<Satis> veri = sa.Verileri_Listeleme();
                    for (Satis c : veri) {
                        if (c.uretim_id == Integer.parseInt(uretim_id.getText()) && c.getFirma_vergi_no().toLowerCase().equals(firma_vergi.getText())) {

                            HavaYoluUlasım d = new HavaYoluUlasım();
                            int satılan_desi = Integer.parseInt(satilan_desi.getText());
                            System.out.println(c.getSatis_id());
                            an = d.run(c.getSatis_id(), satılan_desi);
                        }
                    }

                }
                if (ulasim_yolu.getSelectedItem().toString().toLowerCase().equals("kara")) {
                    an = s.SatisEkleme(Integer.parseInt(uretim_id.getText()), sattigimiz_ulke.getText(), firma_adi.getText(), firma_vergi.getText(), firma_iletisim.getText(), odeme_turu.getText(), ulasim_yolu.getSelectedItem().toString(), Integer.parseInt(ulasim_uzaklik.getText()), Integer.parseInt(satis_fiyat.getText()), Integer.parseInt(satilan_desi.getText()));
                    SqlVeriIslemleriSatis sa = new SqlVeriIslemleriSatis();
                    List<Satis> veri = sa.Verileri_Listeleme();
                    for (Satis c : veri) {

                        if (c.uretim_id == Integer.parseInt(uretim_id.getText()) && c.getFirma_vergi_no().toLowerCase().equals(firma_vergi.getText())) {

                            KaraYoluUlasım d = new KaraYoluUlasım();
                            int satılan_desi = Integer.parseInt(satilan_desi.getText());
                            an = d.run(c.getSatis_id(), satılan_desi);
                        }
                    }
                
                }
                JOptionPane.showMessageDialog(null, an, "Uyarı", JOptionPane.WARNING_MESSAGE);
            }

            tabloGuncelle();
            

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "HATA!", "Uyarı", JOptionPane.WARNING_MESSAGE);
            tabloGuncelle();
        }
    }//GEN-LAST:event_kaydetBtnActionPerformed

    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed
        if (satis_tablo.getSelectedRow() > -1) {
            Satis s = new Satis();
            int satis_id = (int) satis_tablo.getValueAt(satis_tablo.getSelectedRow(), 0);
            String an=s.SatisSil(satis_id);
            JOptionPane.showMessageDialog(null, an, "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            DefaultTableModel model = (DefaultTableModel) satis_tablo.getModel();
            model.setRowCount(0);
            tabloGuncelle();
            
        }
         else if (ulasim_tablo.getSelectedRow() > -1) {
            //ULASIMYAP SIKINTI ÇIKARIYO
            DenizYoluUlasım d=new DenizYoluUlasım();
            int ulasim_id = (int) ulasim_tablo.getValueAt(ulasim_tablo.getSelectedRow(), 0);
            String an=d.UlasımSil(ulasim_id);
            JOptionPane.showMessageDialog(null, an, "Bilgi", JOptionPane.INFORMATION_MESSAGE);
            DefaultTableModel model = (DefaultTableModel) ulasim_tablo.getModel();
            model.setRowCount(0);
            tabloGuncelle();
         }
        

    }//GEN-LAST:event_silBtnActionPerformed

    private void tableChanged(JTable table) {
        
        String an="Girilen Bilgiler Hatalı";
        int row = table.getSelectedRow(); // Seçilen satırın indeksi
        int column = table.getSelectedColumn(); // Seçilen sütunun indeksi
        String cName = table.getColumnName(column);
        Object data = table.getValueAt(row, column); // Seçilen hücrenin değer
        int satis_id = (int) table.getValueAt(table.getSelectedRow(), 0);
        Satis s = new Satis();
        DenizYoluUlasım d = new DenizYoluUlasım();
        
        if (table.equals(satis_tablo)) {
            if (column == 3 || column == 4 || column == 5 || column == 6 || column == 9) {
                an= s.SatisDüzenleme(cName, data.toString().toLowerCase(), satis_id, 0, 0);
            }
            if (column == 12 || column == 13 || column == 14) {
                an= s.SatisDüzenleme(cName, "", satis_id, (Integer) data, 2);
            }
        } else if (table.equals(ulasim_tablo)) {
            if (column == 6) {
                an= d.UlasımGuncelle(cName, data.toString().toLowerCase(), satis_id, 0, 0);                
            }
            if(column==7 && data.toString().toLowerCase().equals("evet") || data.toString().toLowerCase().equals("hayır")){
                an= d.UlasımGuncelle(cName, data.toString().toLowerCase().toUpperCase(), satis_id, 0, 0);
            }
            if (column == 10 || column == 11) {
                 an=d.UlasımGuncelle(cName, "", satis_id, (Integer) data, 2);
            }
        }
        JOptionPane.showMessageDialog(null, an, "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        

        //System.out.println("tc:" + tc);
        //System.out.println(cName);
        //System.out.println(data + ":" + cName + ":" + column);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        tabloGuncelle();

    }

    private void tabloGuncelle() {
        JTable tablo = satis_tablo;
        SqlVeriIslemleriSatis p = new SqlVeriIslemleriSatis();

        List<Satis> veri = p.Verileri_Listeleme();
        DefaultTableModel dfTable = (DefaultTableModel) tablo.getModel();
        dfTable.setRowCount(0);
        for (Satis c : veri) {
            Object[] obj = {c.getSatis_id(), c.getUretim_id(), Character.toUpperCase(c.getSatilan_ulke().charAt(0)) + c.getSatilan_ulke().substring(1), Character.toUpperCase(c.getSattigimiz_ulke().charAt(0)) + c.getSattigimiz_ulke().substring(1), Character.toUpperCase(c.getFirma_adi().charAt(0)) + c.getFirma_adi().substring(1), c.getFirma_vergi_no(), c.getFirma_iletisim(), c.getSatilan_urun(), c.getSatilan_urun_renk(), c.getOdeme_turu(), c.getUlasım_yolu(), c.getUlasım_yolu_uzaklık(), c.getSatis_fiyati(), c.getSatılan_desi()};
            dfTable.addRow(obj);
        }

        JTable ceoTablo = ulasim_tablo;
        SqlVeriIslemleriUlasım yo = new SqlVeriIslemleriUlasım();
        List<UlasımYap> ceoVeri = yo.Verileri_Listeleme();
        DefaultTableModel dfTableD = (DefaultTableModel) ceoTablo.getModel();
        dfTableD.setRowCount(0);
        for (UlasımYap c : ceoVeri) {
            Object[] obj = {c.getUlasim_id(), c.getSatis_id(), Character.toUpperCase(c.getSattigimiz_ulke().charAt(0)) + c.getSattigimiz_ulke().substring(1), Character.toUpperCase(c.getSatilan_urun().charAt(0)) + c.getSatilan_urun().substring(1), Character.toUpperCase(c.getSatilan_renk().charAt(0)) + c.getSatilan_renk().substring(1), Character.toUpperCase(c.getFirma_iletisim().charAt(0)) + c.getFirma_iletisim().substring(1), Character.toUpperCase(c.getUlasım_yolu().charAt(0)) + c.getUlasım_yolu().substring(1), c.getTeslim_edildimi().toUpperCase(), c.getUlasım_yolu_uzaklık(), c.getSatilan_desi(), c.getUlasım_maliyet(), c.getTahmini_teslimat_gunu()};
            dfTableD.addRow(obj);
        }

        SqlVeriIslemleriUretim uretim = new SqlVeriIslemleriUretim();
        List<Uretim> uretimVeri = uretim.Verileri_Listeleme();
        DefaultTableModel uretimTablo = (DefaultTableModel) jTable3.getModel();
        uretimTablo.setRowCount(0);
        for (Uretim c : uretimVeri) {
            Object[] obj = {c.uretim_id, c.urun_id, Character.toUpperCase(c.ulke.charAt(0)) + c.ulke.substring(1), Character.toUpperCase(c.urun_ad.charAt(0)) + c.urun_ad.substring(1), Character.toUpperCase(c.urun_renk.charAt(0)) + c.urun_renk.substring(1), c.satılan_miktar, c.maliyet};
            uretimTablo.addRow(obj);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatisPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firma_adi;
    private javax.swing.JTextField firma_iletisim;
    private javax.swing.JTextField firma_vergi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable3;
    private javax.swing.JButton kaydetBtn;
    private javax.swing.JTextField odeme_turu;
    private javax.swing.JTextField satilan_desi;
    private javax.swing.JTextField satis_fiyat;
    public javax.swing.JTable satis_tablo;
    private javax.swing.JTextField sattigimiz_ulke;
    private javax.swing.JButton silBtn;
    public javax.swing.JTable ulasim_tablo;
    private javax.swing.JTextField ulasim_uzaklik;
    private javax.swing.JComboBox<String> ulasim_yolu;
    private javax.swing.JTextField uretim_id;
    // End of variables declaration//GEN-END:variables
}
